package com.uxpsystems.assignment.entity;
// Generated 24-Nov-2017 12:05:21 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserTbl generated by hbm2java
 */
@Entity
@Table(name = "User_Tbl")
public class UserTbl implements java.io.Serializable {
	@Id
	@Column(name = "id")

	private long id;
	private String username;
	private String password;
	private String status;
	private String role;

	public UserTbl() {
	}

	public UserTbl(long id, String username, String password, String status, String role) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.role = role;
		this.status = status;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
